"""
Django settings for proyecto1 project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n2t=-k4p^$xbt$6bhvu4gev%4)j66nw@vv!sk%82de(c7_b_fd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AuthenticationMiddleware',  # middleware personalizado
    'core.middleware.AdminAccessMiddleware',     # Middleware para admin
    'core.middleware.ClienteAccessMiddleware',
]

ROOT_URLCONF = 'proyecto1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# CONFIGURACIÓN SQLITE PARA DESARROLLO
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MODELO DE USUARIO PERSONALIZADO
AUTH_USER_MODEL = 'core.Usuario'

# COMENTA TODA LA CONFIGURACIÓN DE ORACLE TEMPORALMENTE
'''
# Configuración del Wallet para Oracle Cloud
os.environ['TNS_ADMIN'] = os.path.join(BASE_DIR, 'wallet')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'ECW3GQEFIBLCJ12E_high',
        'USER': 'PROG_WEB_S6',
        'PASSWORD': 'duocUCCL2025',
        'HOST': 'G1DE58456D6E91F_ECW3GQEFIBLCJ12E.adb.oraclecloud.com',
        'PORT': '1522',
        'OPTIONS': {
            'threaded': True,
        }
    }
}
'''


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Configuración de URLs de autenticación
LOGIN_URL = 'login'           # Nombre de tu URL de login
LOGIN_REDIRECT_URL = 'inicio' # Redirigir al inicio después de login
LOGOUT_REDIRECT_URL = 'inicio' # Redirigir al inicio después de logout